import { foo } from "./1.js";
import { foo as foo1 } from "./1 copy 1.js";
import { foo as foo2 } from "./1 copy 3.js";
import { foo as foo3 } from "./1 copy 4.js";
import { foo as foo4 } from "./1 copy 5.js";
import { foo as foo5 } from "./1 copy 6.js";
import { foo as foo6 } from "./1 copy 7.js";
import { foo as foo7 } from "./1 copy 8.js";
import { foo as foo8 } from "./1 copy 9.js";
import { foo as foo9 } from "./1 copy 10.js";
import { foo as foo10 } from "./1 copy 11.js";
// import { foo as foo11 } from "./1 copy 2.js";
